[package]
name = "neq_square_verifier"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.sncast.default]
account = "default"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"